[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
axum = "0.6.20"
tokio = { version = "1.33.0", features = ["full"] }
cloud-storage = "0.11.1"
serde = { version = "1.0.190", features = ["derive"] }
dotenv = "0.15.0"
serde_json = "1.0.108"
